ALTER TABLE "spell" ALTER COLUMN "name" SET NOT NULL;
ALTER TABLE "spell" ALTER COLUMN "casting_time" SET NOT NULL;
ALTER TABLE "spell" ALTER COLUMN "range" SET NOT NULL;
ALTER TABLE "spell" ALTER COLUMN "duration" SET NOT NULL;
ALTER TABLE "spell" ALTER COLUMN "components" SET NOT NULL;
ALTER TABLE "spell" ALTER COLUMN "desc" SET NOT NULL;
ALTER TABLE "spell" ALTER COLUMN "level" SET NOT NULL;
ALTER TABLE "spell" DROP COLUMN IF EXISTS "index";