export const skills = [
  { label: "Acrobatics", value: "Acrobatics" },
  { label: "Animal Handling", value: "Animal Handling" },
  { label: "Arcana", value: "Arcana" },
  { label: "Athletics", value: "Athletics" },
  { label: "Deception", value: "Deception" },
  { label: "History", value: "History" },
  { label: "Insight", value: "Insight" },
  { label: "Intimidation", value: "Intimidation" },
  { label: "Investigation", value: "Investigation" },
  { label: "Medicine", value: "Medicine" },
  { label: "Nature", value: "Nature" },
  { label: "Perception", value: "Perception" },
  { label: "Performance", value: "Performance" },
  { label: "Persuasion", value: "Persuasion" },
  { label: "Religion", value: "Religion" },
  { label: "Sleight of Hand", value: "Sleight of Hand" },
  { label: "Stealth", value: "Stealth" },
  { label: "Survival", value: "Survival" },
]
export const classes = [
  { label: "Artificer", value: "Artificer" },
  { label: "Barbarian", value: "Barbarian" },
  { label: "Bard", value: "Bard" },
  { label: "Blood Hunter", value: "Blood Hunter" },
  { label: "Cleric", value: "Cleric" },
  { label: "Druid", value: "Druid" },
  { label: "Fighter", value: "Fighter" },
  { label: "Monk", value: "Monk" },
  { label: "Paladin", value: "Paladin" },
  { label: "Ranger", value: "Ranger" },
  { label: "Rogue", value: "Rogue" },
  { label: "Sorcerer", value: "Sorcerer" },
  { label: "Warlock", value: "Warlock" },
  { label: "Wizard", value: "Wizard" },
]
